-- Create keep-alive table
CREATE TABLE IF NOT EXISTS keep_alive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text DEFAULT ''::text,
  random uuid DEFAULT gen_random_uuid(),
  last_ping timestamp with time zone DEFAULT now()
);

-- Insert initial placeholder rows
INSERT INTO keep_alive (name) 
VALUES ('placeholder'), ('github-actions-cron')
ON CONFLICT DO NOTHING;

-- Enable RLS (but allow public read for cron)
ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;

-- Allow public read (for cron job)
CREATE POLICY "Allow public read for cron"
  ON keep_alive FOR SELECT
  TO public
  USING (true);

-- Allow public update for last_ping
CREATE POLICY "Allow public update for cron"
  ON keep_alive FOR UPDATE
  TO public
  USING (name = 'github-actions-cron')
  WITH CHECK (name = 'github-actions-cron');